### ISSUE TITLE
Any plans to integrate the makeDOMDriver of Cycle

### ISSUE THREAD

**Issue by kristianmandrup** [justinwoo/purescript-cycle-run#1]
I can see you are using jQuery in your example. I assume it is simply because there is currently nto full integration with the cycle libs such as DOM drivers? Are these in the works/plans?
Cheers!

**Comment by justinwoo** [comment]
Sorry for the late response, apparently I wasn't subscribed to my own repo.

I'm not really sure how I would go about integrating the DOM driver to be honest. I haven't kept up with much of the changes and it would probably involve having to type snabdom and the actual event handling parts from the DOM driver. I've been mostly planning to use this with Halogen or any existing library for the actual front end system, e.g. https://github.com/justinwoo/purescript-cycle-etch-sketch (This demo really needs an update though)

**Comment by justinwoo** [comment]
I don't really use this myself anymore, and the Cycle DOM driver API has chagned quite a bit now I guess.

Nowadays I just use these libraries: https://purescript-resources.readthedocs.io/en/latest/ui.html
